---
title: "Modifying Data Frames in R"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
```

```{r message=FALSE}
# load data frame
dogs <- read_csv('dogs.csv')
```

```{r}
# inspect data frame
head(dogs)
```

```{r}
# rename columns
dogs <- dogs %>%
  rename(popularity_2016 = rank_2016,
         popularity_2015 = rank_2015,
         popularity_2014 = rank_2014,
         popularity_2013 = rank_2013)
colnames(dogs)
```

'''
```{r}
____________________________________________________________________________________________
```

```{r}
# add average height, average weight and rank change columns
dogs <- dogs %>%
  mutate(avg_height = (height_low_inches + height_high_inches)/2, avg_weight = (weight_low_lbs + weight_high_lbs)/2, rank_change_13_to_16 = rank_2016 - rank_2013)
head(dogs)
```

'''
```{r}
____________________________________________________________________________________________
```

```{r message=FALSE}
# add columns and remove existing columns
dogs <- dogs %>%
  transmute(breed = breed,
            avg_height = (height_low_inches + height_high_inches)/2,
            avg_weight = (weight_low_lbs + weight_high_lbs)/2,
            rank_change_13_to_16 = rank_2016 - rank_2013)
```

```{r}
# check column names
original_col_names <- colnames(dogs)
print(original_col_names)
```

```{r}
# rename data frame columns
dogs <- dogs %>%
  rename(avg_height_inches = avg_height, avg_weight_lbs = avg_weight, popularity_change_13_to_16 = rank_change_13_to_16)
```

```{r}
# check column names
new_col_names = colnames(dogs)
print(new_col_names)
```

'''
```{r}
____________________________________________________________________________________________
```

```{r}
# add new columns, drop existing columns and arrange
dogs <- dogs %>%
  transmute(breed = breed, height_average_feet = (height_low_inches + height_high_inches)/24, popularity_change_15_to_16 = rank_2016-rank_2015) %>%
  arrange(desc(popularity_change_15_to_16))
head(dogs) 
```
